version: '3'
services:
  workspace:
    user: root
    env_file: .env
    image: seasketch/geoprocessing-workspace

    # Mount everything we need, because docker containers don't persist anything
    volumes:
      # Common assets
      - ../common:/common:cached
      # Quick file share
      - ../share:/share:cached
      # Bound host volume for data folder, preset to Box Sync used by seasketch team
      # - "~/Box\ Sync:/data:cached"
      # Internal named volume for all code assets.
      - code_volume:/workspaces

    # Keep container running after start
    command: sleep infinity
    # connect db service to network
    network_mode: service:db
    # database connection parameters
    environment:
      PGHOST: "db"
      PGUSER: "docker"
      PGPASSWORD: "docker"
      PGDATABASE: "gis"
  db:
    image: seasketch/geoprocessing-db
    # Port 54320 will be exposed on the host machine for accessing postgis.
    ports:
      - "54320:5432"

# Use named volumes for faster read/write performance
volumes:
  code_volume:
